language: node_js

node_js: "8"


script:
  - npm run pack

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
